---
- ansible.builtin.import_playbook: update.yml

- name : Configure QoS
  gather_facts: false
  hosts:  all
  tasks:

    - name: Configure QoS Class-Maps (NXOS)
      cisco.nxos.nxos_config:
        src: nxos/class_map_qos.j2
      loop: "{{ class_map_qos }}"
      when: class_map_qos is defined and inventory_hostname in groups['nxos']

    - name: Configure QoS Policy-Maps (NXOS)
      cisco.nxos.nxos_config:
        src: nxos/policy_map_qos.j2
      loop: "{{ policy_map_qos }}"
      when: policy_map_qos is defined and inventory_hostname in groups['nxos']

    - name: Configure QoS Queuing Policy-Maps (NXOS)
      cisco.nxos.nxos_config:
        src: nxos/policy_map_queuing.j2
      loop: "{{ policy_map_queuing }}"
      when: policy_map_queuing is defined and inventory_hostname in groups['nxos']

    - name: Configure System Egress Queues (NXOS)
      cisco.nxos.nxos_config:
        src: nxos/system_qos_egress_queues.j2
      loop: "{{ system_qos_queuing_output }}"
      when: system_qos_queuing_output is defined and inventory_hostname in groups['nxos']

    - name: Configure Service Policy Input for Interface (NXOS)
      cisco.nxos.nxos_config:
        lines:
        - "{{ 'service-policy type qos input %s' % item.qos_input }}"
        parents: interface {{ '%s.%s' % (item.interface, item.dot1q | int ) if item.dot1q is defined else item.interface }}
      loop: "{{ interfaces }}"
      when: interfaces is defined and inventory_hostname in groups['nxos'] and item.qos_input is defined and item.qos_input != ''

    - name: save running to startup when modified  (NXOS)
      cisco.nxos.nxos_config:
        save_when: modified
      when: inventory_hostname in groups['nxos']
