---
- name : Update host vars
  gather_facts: false
  hosts: localhost

  tasks:

    - name: Update host vars
      ansible.builtin.shell: source ~/venv/bin/activate; python3 ./generate_yaml.py
      delegate_to: localhost